---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgres-volume
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  storageClassName: awx-postgres-volume
  hostPath:
    path: /etc/data/postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-projects-volume
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 50Gi
  storageClassName: awx-projects-volume
  hostPath:
    path: /etc/data/projects
