---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: automation
spec:
  replicas: 1
  admin_user: admin
  admin_password_secret: awx-admin-password

  ingress_type: ingress
  ingress_tls_secret: awx-fqdn-secret-tls
  hostname: awx.krakow.igk.intel.com

  postgres_configuration_secret: awx-postgres-configuration

  postgres_storage_class: awx-postgres-volume
  postgres_storage_requirements:
    requests:
      storage: 10Gi
  projects_persistence: true
  projects_existing_claim: awx-projects-claim
